spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

  # sept 30
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/onlineorder
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATBASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:database-init.sql"

  cache:
    caffeine:
      spec: expireAfterWrite=60s

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: TRACE # Incoming HTTP requests
                                                      # it can have multiple HTTP requests
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.jdbc.core: DEBUG  # SQL
#    datasource:
#    url:
#    username:
#    password:
#    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#    mode:
#    schema-Locations verasspath: "classpath:database-int-sql"
#  cache:
#    caffeine:
#      spec: expireAfterWrite=1m
#logging:
#  level:
#    org.springframework.jdbc.core: DEBUG # SQL
#    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests